[tool.poetry]
name = "dublaja-backend"
version = "0.1.0"
description = "Free game voice dubbing & TTS backend"
authors = ["Dublaja"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.115.0"}
uvicorn = {extras = ["standard"], version = "^0.32.0"}
python-multipart = "^0.0.12"
gtts = "^2.5.3"
edge-tts = "^7.0.0"
deep-translator = "^1.11.4"
SpeechRecognition = "^3.10.4"
pydub = "^0.25.1"
numpy = "^1.26.0"
static-ffmpeg = "^2.13"
httpx = "^0.27.0"
msgpack = "^1.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
